FROM mcr.microsoft.com/devcontainers/base:bullseye

ARG PHP_VERSION="${templateOption:phpVersion}"
ARG COMPOSER_VERSION="${templateOption:composerVersion}"
ARG NODE_VERSION=--lts

# Install php from sury
RUN curl -sS https://packages.sury.org/php/apt.gpg | apt-key add - \
    && echo "deb https://packages.sury.org/php/ bullseye main" | tee /etc/apt/sources.list.d/php.list

RUN apt-get update && apt-get install -y \
    libzip-dev \
    git \
    unzip \
    wget \
    libfreetype6-dev \
    libicu-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libxslt1-dev \
    mariadb-client \
    sendmail-bin \
    sendmail \
    sudo \
    redis \
    vim \
    curl \
    libmagickwand-dev \
    imagemagick \
    libjpeg-dev \
    \
    php${PHP_VERSION}-fpm \
    php${PHP_VERSION}-zip \
    php${PHP_VERSION}-simplexml \
    php${PHP_VERSION}-curl \
    php${PHP_VERSION}-intl \
    php${PHP_VERSION}-soap \
    php${PHP_VERSION}-bcmath \
    php${PHP_VERSION}-gd \
    php${PHP_VERSION}-mysql \
    php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-swoole \
    php${PHP_VERSION}-xdebug \
    \
    libnss3-tools \
    inotify-tools \
    \
    && apt clean

# configure php
RUN echo 'memory_limit = 2G' >> /etc/php/${PHP_VERSION}/fpm/php.ini \
    && echo 'max_input_vars = 10000' >> /etc/php/${PHP_VERSION}/fpm/php.ini \
    && echo 'memory_limit = -1' >> /etc/php/${PHP_VERSION}/fpm/conf.d/memory_limit.ini \
    && echo 'memory_limit = 2G' >> /etc/php/${PHP_VERSION}/cli/php.ini \
    && echo 'max_input_vars = 10000' >> /etc/php/${PHP_VERSION}/cli/php.ini \
    && echo 'memory_limit = -1' >> /etc/php/${PHP_VERSION}/cli/conf.d/memory_limit.ini

RUN mkdir -p /run/php

COPY conf/php-fpm/fpm-pool.conf /etc/php/${PHP_VERSION}/fpm/pool.d/www.conf

RUN ln -s /usr/sbin/php-fpm${PHP_VERSION} /usr/sbin/php-fpm

# mkcert
RUN ARCH=$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/') \
    && curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/$ARCH" \
    && chmod +x mkcert-v*-linux-* \
    && cp mkcert-v*-linux-* /usr/local/bin/mkcert

# composer
RUN curl -sS https://getcomposer.org/installer \
    | php -- --install-dir=/usr/local/bin --filename=composer $( [ "$COMPOSER_VERSION" != "latest-stable" ] && echo "--version=$COMPOSER_VERSION" )
RUN composer --version

# n98-magerun2
RUN curl -o /usr/local/bin/n98 https://files.magerun.net/n98-magerun2.phar && chmod +x /usr/local/bin/n98

# xdebug config
COPY conf/php/99-xdebug.ini /etc/php/${PHP_VERSION}/fpm/conf.d/99-xdebug.ini
COPY conf/php/99-xdebug.ini /etc/php/${PHP_VERSION}/cli/conf.d/99-xdebug.ini

# SSH known hosts for GitHub and Bitbucket
RUN mkdir -p ~/.ssh/ \
    && curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts \
    && curl https://bitbucket.org/site/ssh >> ~/.ssh/known_hosts

# mailhog sendmail
RUN apt update && apt install -y golang \
    && go get github.com/mailhog/mhsendmail \
    && apt -y remove golang && apt autoclean \
    && cp ~/go/bin/mhsendmail /usr/bin/mhsendmail \
    && echo 'sendmail_path ="mhsendmail --smtp-addr=127.0.0.1:1025"' >> /etc/php/${PHP_VERSION}/fpm/php.ini \
    && echo 'sendmail_path ="mhsendmail --smtp-addr=127.0.0.1:1025"' >> /etc/php/${PHP_VERSION}/cli/php.ini

# Node.js via nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && \
    export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    nvm install $NODE_VERSION && \
    nvm use $NODE_VERSION && \
    npm install -g npm@latest

ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH

# gh CLI
RUN sudo mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& sudo mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y && sudo apt clean

RUN echo 'export WORKSPACE_DIR=$(pwd)' >> /root/.bashrc \
    && echo '[ -f "$WORKSPACE_DIR/.env" ] && source "$WORKSPACE_DIR/.env"' >> /root/.bashrc
