FROM nginx:latest

RUN curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
RUN chmod +x mkcert-v*-linux-amd64
RUN cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert

RUN mkcert -install && mkcert -cert-file /etc/ssl/certs/localhost.crt -key-file /etc/ssl/private/localhost.key localhost

COPY conf/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY conf/nginx/magento.conf /var/www/magento.conf
